-- 月结核对 / POS 月销量
-- 1) 出库类型：正常销售、签单、FOC、厨房、员工、招待、其他
alter table public.inventory_logs
  add column if not exists out_type text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname='inventory_logs_out_type_check'
      and conrelid='public.inventory_logs'::regclass
  ) then
    alter table public.inventory_logs
      add constraint inventory_logs_out_type_check
      check (out_type is null or out_type in ('NORMAL','CREDIT','FOC','KITCHEN','STAFF','ENT','OTHER'));
  end if;
end $$;

-- 2) 每月 POS 销量，仅用于对账，不修改库存。
create table if not exists public.monthly_pos_sales (
  id bigint generated by default as identity primary key,
  month_key text not null,
  item_id uuid not null references public.inventory_items(id) on delete cascade,
  item_name text not null,
  pos_quantity numeric not null default 0 check (pos_quantity >= 0),
  updated_by text not null default '',
  updated_at timestamptz not null default now(),
  unique(month_key,item_id),
  constraint monthly_pos_sales_month_key_check check (month_key ~ '^[0-9]{4}-[0-9]{2}$')
);

alter table public.monthly_pos_sales enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='monthly_pos_sales' and policyname='active users can read monthly pos sales') then
    create policy "active users can read monthly pos sales" on public.monthly_pos_sales for select to authenticated using (is_app_active());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='monthly_pos_sales' and policyname='active users can insert monthly pos sales') then
    create policy "active users can insert monthly pos sales" on public.monthly_pos_sales for insert to authenticated with check (is_app_active());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='monthly_pos_sales' and policyname='active users can update monthly pos sales') then
    create policy "active users can update monthly pos sales" on public.monthly_pos_sales for update to authenticated using (is_app_active()) with check (is_app_active());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='monthly_pos_sales' and policyname='active users can delete monthly pos sales') then
    create policy "active users can delete monthly pos sales" on public.monthly_pos_sales for delete to authenticated using (is_app_active());
  end if;
end $$;

grant select,insert,update,delete on public.monthly_pos_sales to authenticated;
grant usage,select on sequence public.monthly_pos_sales_id_seq to authenticated;
